/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package simpanan;

import anggota.CariAnggota;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.koneksi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.HashMap;
import java.util.Map;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author Lenovo
 */
public class Simpanan extends javax.swing.JDialog {
    private StringBuilder htmlContent;
    private CariAnggota carianggota=new CariAnggota(null,false);
    private String idAnggota = "";
    /**
     * Creates new form Anggota
     * @param parent
     * @param modal
     */
    public Simpanan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8,1);
        setSize(885,674);
        
        HTMLEditorKit kit = new HTMLEditorKit();
//      LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #DDDDDD;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #DDDDDD;background: #ffffff;color:#323232;}"
        );
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        ChkInput.setSelected(false);
        isForm(); 
        
        carianggota.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(carianggota.getTable().getSelectedRow()!= -1){                   
                    TtambahAnggotaSimpanan.setText(carianggota.tbAnggota.getValueAt(carianggota.tbAnggota.getSelectedRow(),3).toString());
                    idAnggota = carianggota.tbAnggota.getValueAt(carianggota.tbAnggota.getSelectedRow(),0).toString();
                }
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        LoadHTML = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        panelGlass8 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnBatal = new widget.Button();
        BtnHapus = new widget.Button();
        BtnEdit = new widget.Button();
        BtnPrint = new widget.Button();
        BtnAll = new widget.Button();
        jLabel10 = new widget.Label();
        LCount = new widget.Label();
        BtnKeluar = new widget.Button();
        panelGlass9 = new widget.panelisi();
        jLabel16 = new widget.Label();
        cmbCrJumlahdata = new javax.swing.JComboBox<>();
        jLabel7 = new widget.Label();
        TCariTahun = new javax.swing.JTextField();
        jLabel6 = new widget.Label();
        TCari = new javax.swing.JTextField();
        BtnCari = new widget.Button();
        PanelInput = new javax.swing.JPanel();
        FormInput = new widget.PanelBiasa();
        jnL = new javax.swing.JLabel();
        TtambahSimpanan = new javax.swing.JTextField();
        TtambahAnggotaSimpanan = new javax.swing.JTextField();
        jnL1 = new javax.swing.JLabel();
        BtnAddAnggotaSimpanan = new widget.Button();
        BtnCariAnggota = new widget.Button();
        ChkInput = new widget.CekBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(611, 155));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Data Simpanan ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        LoadHTML.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        LoadHTML.setForeground(new java.awt.Color(50, 50, 50));
        LoadHTML.setName("LoadHTML"); // NOI18N
        Scroll.setViewportView(LoadHTML);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(44, 100));
        jPanel3.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass8.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnSimpan);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        BtnBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnBatalKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnBatal);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnHapus);

        BtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/inventaris.png"))); // NOI18N
        BtnEdit.setMnemonic('G');
        BtnEdit.setText("Ganti");
        BtnEdit.setToolTipText("Alt+G");
        BtnEdit.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        BtnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEditKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnEdit);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnPrint);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('M');
        BtnAll.setText("Semua");
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnAll);

        jLabel10.setText("Record :");
        jLabel10.setPreferredSize(new java.awt.Dimension(70, 30));
        panelGlass8.add(jLabel10);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LCount.setPreferredSize(new java.awt.Dimension(72, 30));
        panelGlass8.add(LCount);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        jPanel3.add(panelGlass8, java.awt.BorderLayout.CENTER);

        panelGlass9.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel16.setText("Jumlah Data :");
        jLabel16.setPreferredSize(new java.awt.Dimension(85, 23));
        panelGlass9.add(jLabel16);

        cmbCrJumlahdata.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        cmbCrJumlahdata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "25", "50", "100", "1000" }));
        cmbCrJumlahdata.setBorder(new com.formdev.flatlaf.ui.FlatTextBorder());
        cmbCrJumlahdata.setMinimumSize(new java.awt.Dimension(94, 23));
        cmbCrJumlahdata.setPreferredSize(new java.awt.Dimension(96, 23));
        cmbCrJumlahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCrJumlahdataActionPerformed(evt);
            }
        });
        panelGlass9.add(cmbCrJumlahdata);

        jLabel7.setText("Tahun :");
        jLabel7.setPreferredSize(new java.awt.Dimension(60, 23));
        panelGlass9.add(jLabel7);

        TCariTahun.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TCariTahun.setPreferredSize(new java.awt.Dimension(100, 22));
        panelGlass9.add(TCariTahun);

        jLabel6.setText("Key Word :");
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass9.add(jLabel6);

        TCari.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TCari.setPreferredSize(new java.awt.Dimension(240, 22));
        panelGlass9.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('2');
        BtnCari.setToolTipText("Alt+2");
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnCari);

        jPanel3.add(panelGlass9, java.awt.BorderLayout.PAGE_START);

        internalFrame1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        PanelInput.setOpaque(false);
        PanelInput.setPreferredSize(new java.awt.Dimension(850, 100));
        PanelInput.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setPreferredSize(new java.awt.Dimension(850, 137));
        FormInput.setLayout(null);

        jnL.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jnL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jnL.setText("Tambah Anggota Simpanan :");
        FormInput.add(jnL);
        jnL.setBounds(360, 30, 150, 23);
        FormInput.add(TtambahSimpanan);
        TtambahSimpanan.setBounds(130, 30, 210, 23);
        FormInput.add(TtambahAnggotaSimpanan);
        TtambahAnggotaSimpanan.setBounds(520, 30, 210, 23);

        jnL1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jnL1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jnL1.setText("Tambah Simpanan :");
        FormInput.add(jnL1);
        jnL1.setBounds(10, 30, 110, 23);

        BtnAddAnggotaSimpanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/plus_16.png"))); // NOI18N
        BtnAddAnggotaSimpanan.setMnemonic('2');
        BtnAddAnggotaSimpanan.setToolTipText("Alt+2");
        BtnAddAnggotaSimpanan.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAddAnggotaSimpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddAnggotaSimpananActionPerformed(evt);
            }
        });
        BtnAddAnggotaSimpanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAddAnggotaSimpananKeyPressed(evt);
            }
        });
        FormInput.add(BtnAddAnggotaSimpanan);
        BtnAddAnggotaSimpanan.setBounds(780, 30, 28, 23);

        BtnCariAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnCariAnggota.setMnemonic('1');
        BtnCariAnggota.setToolTipText("ALt+1");
        BtnCariAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariAnggotaActionPerformed(evt);
            }
        });
        FormInput.add(BtnCariAnggota);
        BtnCariAnggota.setBounds(740, 30, 28, 23);

        PanelInput.add(FormInput, java.awt.BorderLayout.CENTER);

        ChkInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setMnemonic('I');
        ChkInput.setText(".: Input Data");
        ChkInput.setToolTipText("Alt+I");
        ChkInput.setBorderPainted(true);
        ChkInput.setBorderPaintedFlat(true);
        ChkInput.setFocusable(false);
        ChkInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChkInput.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChkInput.setPreferredSize(new java.awt.Dimension(192, 20));
        ChkInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkInputActionPerformed(evt);
            }
        });
        PanelInput.add(ChkInput, java.awt.BorderLayout.PAGE_END);

        internalFrame1.add(PanelInput, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        LoadHTML.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            String URL = koneksi.HOST() + "/api/v1/savings";
            System.out.println("Request ke: " + URL);

            // Ambil token dari Preferences
            Preferences prefs = Preferences.userRoot().node("myApp");
            String token = prefs.get("auth_token", null);

            if (token == null) {
                JOptionPane.showMessageDialog(null, "Token tidak ditemukan! Harap login terlebih dahulu.");
                return;
            }

            // Header
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.set("Accept", "application/json");
            headers.set("Authorization", "Bearer " + token);

            // Data Anggota
            Map<String, Object> requestData = new HashMap<>();
            requestData.put("tahun", TtambahSimpanan.getText());

            // Konversi Map ke JSON String menggunakan ObjectMapper
            ObjectMapper objectMapper = new ObjectMapper();
            String requestJsonAnggota = objectMapper.writeValueAsString(requestData);

            // Request menggunakan RestTemplate
            RestTemplate restAnggota = new RestTemplate();
            HttpEntity<String> entity = new HttpEntity<>(requestJsonAnggota, headers);
            ResponseEntity<String> response = restAnggota.exchange(URL, HttpMethod.POST, entity, String.class);
            
            // Menangani response
            if (response.getStatusCode() == HttpStatus.CREATED) {
                JsonNode root = objectMapper.readTree(response.getBody());
                JOptionPane.showMessageDialog(null, root.path("message").asText());
                tampil(TCariTahun.getText(), cmbCrJumlahdata.getSelectedItem().toString());
            } else {
                JOptionPane.showMessageDialog(null, "Gagal simpan, periksa kembali data");
            }
        } catch (HttpClientErrorException e) { 
            // Menangani error dari API (misalnya 400 Bad Request)
            System.out.println("Error Response: " + e.getResponseBodyAsString());
            JOptionPane.showMessageDialog(null, e.getResponseBodyAsString());
        } catch (JsonProcessingException | HeadlessException | RestClientException e) {
            System.out.println("Terjadi kesalahan: " + e.getMessage());
        }
        setCursor(Cursor.getDefaultCursor());
        LoadHTML.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnSimpanActionPerformed(null);
        }else{
            //            Valid.pindah(evt,KdJbtn,BtnBatal);
        }
    }//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        ChkInput.setSelected(true);
        isForm();
        emptTeks();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnBatalKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            emptTeks();
        }
    }//GEN-LAST:event_BtnBatalKeyPressed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                String URL = koneksi.HOST() + "/api/v1/savings/" + TCariTahun.getText();
                System.out.println("Request ke: " + URL);

                // Ambil token dari Preferences
                Preferences prefs = Preferences.userRoot().node("myApp");
                String token = prefs.get("auth_token", null);

                if (token == null) {
                    System.out.println("Token tidak ditemukan! Harap login terlebih dahulu.");
                    return;
                }

                // Header
                HttpHeaders headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);
                headers.set("Accept", "application/json");
                headers.set("Authorization", "Bearer " + token); 

                // Request menggunakan RestTemplate
                RestTemplate restTemplate = new RestTemplate();
                HttpEntity<String> entity = new HttpEntity<>(headers);
                ResponseEntity<String> response = restTemplate.exchange(URL, HttpMethod.DELETE, entity, String.class);

                ObjectMapper objectMapper = new ObjectMapper();

                if (response.getStatusCode() == HttpStatus.OK) {
                    JsonNode root = objectMapper.readTree(response.getBody());
                    JOptionPane.showMessageDialog(null, root.path("message").asText());
                    tampil(TCariTahun.getText(), cmbCrJumlahdata.getSelectedItem().toString());
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal hapus data");
                }

            } catch (JsonProcessingException | RestClientException e) {
                System.out.println(e);
            }
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnHapusActionPerformed(null);
        }
    }//GEN-LAST:event_BtnHapusKeyPressed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed

    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEditKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnEditActionPerformed(null);
        }
    }//GEN-LAST:event_BtnEditKeyPressed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed

    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }
    }//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnAllActionPerformed(null);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil(TCariTahun.getText(), cmbCrJumlahdata.getSelectedItem().toString());
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnCariActionPerformed(null);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void ChkInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkInputActionPerformed
        isForm();
    }//GEN-LAST:event_ChkInputActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tampil(TCariTahun.getText(), cmbCrJumlahdata.getSelectedItem().toString());
    }//GEN-LAST:event_formWindowOpened

    private void cmbCrJumlahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCrJumlahdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCrJumlahdataActionPerformed

    private void BtnAddAnggotaSimpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddAnggotaSimpananActionPerformed
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        LoadHTML.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            String URL = koneksi.HOST() + "/api/v1/savings/" + TCariTahun.getText() + "/add-member";
            System.out.println("Request ke: " + URL);

            // Ambil token dari Preferences
            Preferences prefs = Preferences.userRoot().node("myApp");
            String token = prefs.get("auth_token", null);

            if (token == null) {
                JOptionPane.showMessageDialog(null, "Token tidak ditemukan! Harap login terlebih dahulu.");
                return;
            }

            // Header
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.set("Accept", "application/json");
            headers.set("Authorization", "Bearer " + token);

            // Data Anggota
            Map<String, Object> requestData = new HashMap<>();
            requestData.put("member_profile_id", idAnggota);

            // Konversi Map ke JSON String menggunakan ObjectMapper
            ObjectMapper objectMapper = new ObjectMapper();
            String requestJsonAnggota = objectMapper.writeValueAsString(requestData);
            
            System.err.println(requestJsonAnggota);
            
            // Request menggunakan RestTemplate
            RestTemplate restAnggota = new RestTemplate();
            HttpEntity<String> entity = new HttpEntity<>(requestJsonAnggota, headers);
            ResponseEntity<String> response = restAnggota.exchange(URL, HttpMethod.POST, entity, String.class);
            
            // Menangani response
            if (response.getStatusCode() == HttpStatus.CREATED) {
                JsonNode root = objectMapper.readTree(response.getBody());
                JOptionPane.showMessageDialog(null, root.path("message").asText());
                tampil(TCariTahun.getText(), cmbCrJumlahdata.getSelectedItem().toString());
            } else {
                JOptionPane.showMessageDialog(null, "Gagal simpan, periksa kembali data");
            }
        } catch (HttpClientErrorException e) { 
            // Menangani error dari API (misalnya 400 Bad Request)
            System.out.println("Error Response: " + e.getResponseBodyAsString());
            JOptionPane.showMessageDialog(null, e.getResponseBodyAsString());
        } catch (JsonProcessingException | HeadlessException | RestClientException e) {
            System.out.println("Terjadi kesalahan: " + e.getMessage());
        } finally {
            idAnggota = "";
            TtambahAnggotaSimpanan.setText("");
        }
        setCursor(Cursor.getDefaultCursor());
        LoadHTML.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnAddAnggotaSimpananActionPerformed

    private void BtnAddAnggotaSimpananKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAddAnggotaSimpananKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddAnggotaSimpananKeyPressed

    private void BtnCariAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariAnggotaActionPerformed
        carianggota.emptTeks();
        carianggota.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
        carianggota.setLocationRelativeTo(internalFrame1);
        carianggota.setAlwaysOnTop(false);
        carianggota.setVisible(true);
    }//GEN-LAST:event_BtnCariAnggotaActionPerformed

    public void emptTeks() {

    }
    
     private void isForm(){
        if(ChkInput.isSelected()==true){
            ChkInput.setVisible(false);
            PanelInput.setPreferredSize(new Dimension(WIDTH,100));
            FormInput.setVisible(true);      
            ChkInput.setVisible(true);
        }else if(ChkInput.isSelected()==false){           
            ChkInput.setVisible(false);            
            PanelInput.setPreferredSize(new Dimension(WIDTH,20));
            FormInput.setVisible(false);      
            ChkInput.setVisible(true);
        }
    }
     
    private void tampil(String tahun, String jumlahData) {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        LoadHTML.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
        try {
           htmlContent = new StringBuilder();
           htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' rowspan='2'>Unit Kerja</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' rowspan='2'>Nomor Anggota</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' rowspan='2'>Nama Anggota</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' rowspan='2'>Tahun</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>Januari</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>Februari</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>Maret</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>April</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>Mei</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>Juni</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>Juli</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>Agustus</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>September</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>Oktober</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>November</td>"+ 
                    "<td valign='middle' bgcolor='#F7F7F7' align='center' colspan='4'>Desember</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Pokok</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Wajib</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Sukarela</td>"+
                    "<td valign='middle' bgcolor='#F7F7F7' align='center'>Dana Sosial</td>"+
                "</tr>"
            );
           try {
               this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                String URL = koneksi.HOST() + "/api/v1/savings?tahun=" + tahun + "&per_page=" + jumlahData;
                System.out.println("Request ke: " + URL);

                            // Ambil token dari Preferences
                Preferences prefs = Preferences.userRoot().node("myApp");
                String token = prefs.get("auth_token", null);

                if (token == null) {
                    System.out.println("Token tidak ditemukan! Harap login terlebih dahulu.");
                    return;
                }

                // Header
                HttpHeaders headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);
                headers.set("Accept", "application/json");
                headers.set("Authorization", "Bearer " + token); 

                // Request menggunakan RestTemplate
                RestTemplate restTemplate = new RestTemplate();
                HttpEntity<String> entity = new HttpEntity<>(headers);
                ResponseEntity<String> response = restTemplate.exchange(URL, HttpMethod.GET, entity, String.class);

                // Parsing JSON ke dalam tabel
                ObjectMapper objectMapper = new ObjectMapper();
                JsonNode rootNode = objectMapper.readTree(response.getBody());

                System.out.println(rootNode);

                JsonNode dataArray = rootNode.path("data");

                if (dataArray.isArray()) {
                for (JsonNode member : dataArray) {
                    String unitkerja = member.path("work_unit").asText();
                    String nomoranggota = member.path("nomor_anggota").asText();
                    String namalengkap = member.path("nama_lengkap").asText();
                    String tahunSimpanan = member.path("tahun").asText();
                    JsonNode dataSimpanan = member.path("savings");

                    // Mulai baris tabel
                    htmlContent.append("<tr class='isi'>")
                        .append("<td valign='middle' bgcolor='#FFFFFF' align='center'>").append(unitkerja).append("</td>")
                        .append("<td valign='middle' bgcolor='#FFFFFF' align='center'>").append(nomoranggota).append("</td>")
                        .append("<td valign='middle' bgcolor='#FFFFFF' align='center'>").append(namalengkap).append("</td>")
                        .append("<td valign='middle' bgcolor='#FFFFFF' align='center'>").append(tahunSimpanan).append("</td>");

                    // Loop untuk menambahkan kolom savings jika ada
                    if (dataSimpanan.isArray()) {
                        for (JsonNode saving : dataSimpanan) {
                            String pokok = saving.path("pokok").asText("-");
                            String wajib = saving.path("wajib").asText("-");
                            String sukarela = saving.path("sukarela").asText("-");
                            String danaSosial = saving.path("dana_sosial").asText("-");

                            htmlContent
                                    .append("<td valign='middle' bgcolor='#FFFFFF' align='center'>")
                                    .append((pokok != null && pokok.equals("0.00")) ? "" : (pokok != null ? pokok : "-"))
                                    .append("</td>")
                                    .append("<td valign='middle' bgcolor='#FFFFFF' align='center'>")
                                    .append((wajib != null && wajib.equals("0.00")) ? "" : (wajib != null ? wajib : "-"))
                                    .append("</td>")
                                    .append("<td valign='middle' bgcolor='#FFFFFF' align='center'>")
                                    .append((sukarela != null && sukarela.equals("0.00")) ? "" : (sukarela != null ? sukarela : "-"))
                                    .append("</td>")
                                    .append("<td valign='middle' bgcolor='#FFFFFF' align='center'>")
                                    .append((danaSosial != null && danaSosial.equals("0.00")) ? "" : (danaSosial != null ? danaSosial : "-"))
                                    .append("</td>");
                        }
                    }

                    // Tutup baris
                    htmlContent.append("</tr>");
                }
            }

            } catch (JsonProcessingException | RestClientException e) {
                System.out.println(e);
            }
            LoadHTML.setText(
                "<html>"+
                  "<head>"+
                    "<style>"+
                        "table { width: auto; table-layout: auto; border-collapse: collapse; border-spacing: 0; }"+
                        "th, td { padding: 4px; text-align: center; white-space: nowrap; }"+
                        "td { word-wrap: break-word; }"+
                    "</style>"+
                  "</head>"+
                  "<body>"+
                    "<table align='center' class='tbl_form'>"+
                      htmlContent.toString()+
                    "</table>"+
                  "</body>"+
                "</html>"
            );
            LoadHTML.setCursor(Cursor.getDefaultCursor());
            LoadHTML.setCaretPosition(0);
            setCursor(Cursor.getDefaultCursor());
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAddAnggotaSimpanan;
    private widget.Button BtnAll;
    private widget.Button BtnBatal;
    private widget.Button BtnCari;
    private widget.Button BtnCariAnggota;
    private widget.Button BtnEdit;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.Button BtnSimpan;
    private widget.CekBox ChkInput;
    private widget.PanelBiasa FormInput;
    private widget.Label LCount;
    private javax.swing.JEditorPane LoadHTML;
    private javax.swing.JPanel PanelInput;
    private widget.ScrollPane Scroll;
    private javax.swing.JTextField TCari;
    private javax.swing.JTextField TCariTahun;
    private javax.swing.JTextField TtambahAnggotaSimpanan;
    private javax.swing.JTextField TtambahSimpanan;
    private javax.swing.JComboBox<String> cmbCrJumlahdata;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private widget.Label jLabel16;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jnL;
    private javax.swing.JLabel jnL1;
    private widget.panelisi panelGlass8;
    private widget.panelisi panelGlass9;
    // End of variables declaration//GEN-END:variables
}
